### ISSUE TITLE
运行comment.py文件会报错

### ISSUE THREAD

**Issue by arrogant-create** [python3xxx/weibo_spider#5]

**Comment by renektonwu** [comment]
加上你的cookie试一下

**Comment by arrogant-create** [comment]
还是没有用，错误结果如下
Traceback (most recent call last):
&nbsp; File "f:\VsCode\Docunmet\python\weibo\weibo_spider-master_comment\weibo_spider-master\weibo_comment.py", line 99, in <module&gt;
&nbsp; &nbsp; resp = json.loads(resp.text)
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
&nbsp; &nbsp; return _default_decoder.decode(s)
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
&nbsp; &nbsp; obj, end = self.raw_decode(s, idx=_w(s, 0).end())
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
&nbsp; &nbsp; raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "python3xxx/weibo_spider"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月18日(星期六) 晚上6:58
收件人:&nbsp;"python3xxx/weibo_spider"<weibo_spider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [python3xxx/weibo_spider] 运行comment.py文件会报错 (#5)





 
加上你的cookie试一下
